# Use actions runner as a base
FROM ghcr.io/actions/actions-runner:latest

USER root

# Update package lists
RUN apt-get update -q

# Install AWS CLI, Git, curl, jq, apt transport, ca certificates, gnupg, lsb release, wget, unzip
RUN apt-get install -y -q awscli git curl jq apt-transport-https ca-certificates gnupg lsb-release wget unzip python3.11

# Install Terraform for AMD64
RUN wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip && \
    unzip terraform_1.5.7_linux_amd64.zip -d /usr/local/bin/ && \
    rm terraform_1.5.7_linux_amd64.zip

# Clean up
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

USER runner
