githubConfigUrl: "https://github.com/Lucas-Hughes/github-arc-runners"
githubConfigSecret: "github-auth-config"

containerMode:
  type: "dind"

template:
  spec:
    containers:
    - name: runner
      image: "lucasjhughes/base-arc-runner:1.0"
      imagePullPolicy: IfNotPresent
      command: ["/home/runner/run.sh"]
